### PR TITLE
Update cpr repos to upstream

### PR DESCRIPTION
**Pull request by jimman2003**
Newer version..Tests passing!

### CODE REVIEW

**Comment by jimman2003** [comment]
Should I move this PR to upstream zsync2?

**Comment by NiLuJe** [comment]
Possibly, yeah ;).

(Also, my bad, I somehow managed to miss the notification for this PR altogether o_O).

**Comment by jimman2003** [comment]
Oh well it happens..

**Comment by NiLuJe** [comment]
FWIW, regardless of the outcome, I'll merge this one way or another the next time I resync w/ upstream ;).

**Comment by jimman2003** [comment]
FYI the pr uses upstream cpr , not AppImage/cpr upstream!

**Pull request closed without merging**
